[package]
name = "yeahson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"

[workspace]
members = ["benchmarks", "xtask"]

[profile.bench]
lto = true
debug = true

[profile.release]
lto = true
debug = true
